create table book
(
    id             int8 generated by default as identity,
    author_name    varchar(255),
    page_count     int4,
    publication    varchar(255),
    published_date timestamp,
    title          varchar(255),
    primary key (id)
)